### ISSUE TITLE
Stuck on modem_5g.bin

### ISSUE THREAD

**Issue by bdotq** [corsicanu/9820-bootloaders_and_modems#4]
Been trying to flash the latest odin release on an S10e, but keeps hanging on modem_5g.bin

**Comment by bdotq** [comment]
resolved. redownloaded. package probably corrupted. 🤦

**Comment by corsicanu** [comment]
> resolved. redownloaded. package probably corrupted. 🤦
> 
> also protip to anyone that might be reading this - be sure to download not just the latest release, but the one that starts with your model number.

Will add that to instructions in the main page to avoid further confusion. Glad you fixed it. Regards!
